package health.medunited.service;

import java.util.Date;

import org.junit.jupiter.api.Test;

import health.medunited.event.NoteEvent;

public class FHIRUpdaterTest {
    @Test    
    public void testUpdate() {
        FHIRUpdater fhirUpdater = new FHIRUpdater();
        fhirUpdater.addNoteToFhirResource(new NoteEvent("eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjS0NoRF9RY3A5OHdnaHlldTlDcHlfQk1OUjVacXBJSHdaUUlGZzJCVkxFIn0.eyJleHAiOjE2NjczMDQwOTcsImlhdCI6MTY2NzMwMzc5NywiYXV0aF90aW1lIjoxNjY3MzAzNDM1LCJqdGkiOiIxZjU1M2M0Yi0zNGUxLTQzNTctYTY1OS1lNjUyZGQzMGJjNzgiLCJpc3MiOiJodHRwczovL2lkLm1lZC11bml0ZWQuaGVhbHRoL3JlYWxtcy9tZWQtdW5pdGVkIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjQ5MzAzMmJjLWQ4YTQtNDVmNy05NTNiLTVjNmMwMjRlNzI3NSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImZoaXIiLCJub25jZSI6IjUzMmUxMmNmLTEzMzMtNDgxNC04NTFhLTRiNzQ1OTc1NTRkMCIsInNlc3Npb25fc3RhdGUiOiJmZjQ3ZGY3Mi0yYjljLTQyZTYtODIwZi1kNjA3NGY0ODkzYWYiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHBzOi8vZmhpci5tZWQtdW5pdGVkLmhlYWx0aCIsImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MSIsImh0dHBzOi8vY2FyZS5tZWQtdW5pdGVkLmhlYWx0aCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtbWVkLXVuaXRlZCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiJmZjQ3ZGY3Mi0yYjljLTQyZTYtODIwZi1kNjA3NGY0ODkzYWYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiY2l0eSI6IkJlcmxpbiIsInBob25lIjoiKzQ5MTczNjMyMjYyMSIsInN0cmVldCI6IkFjaGVuc2Vld2VnIDUwIiwicG9zdGFsQ29kZSI6IjEyMjA5IiwibmFtZSI6Ik1hbnVlbCBCbGVjaHNjaG1pZHQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYW51ZWwuYmxlY2hzY2htaWR0QGdteC5kZSIsImdpdmVuX25hbWUiOiJNYW51ZWwiLCJmYW1pbHlfbmFtZSI6IkJsZWNoc2NobWlkdCIsImVtYWlsIjoibWFudWVsLmJsZWNoc2NobWlkdEBnbXguZGUifQ.QybYDdwiFg1r8PuG1TlKe7pJUuRdOjfv1HUzoLSQmpCAQdfEr2XO6ubk62iXi6_XwTy6OsCYjiOqJYYkfFQZ8K3yk0-KHFIcrdUmUwJvLi3pDqtBi4nwwx1v8HuyfTT-gCGrASZk9qr3gMfefkTYGQr8mpG-XFXy3YVcB-gKNIQHQpqEafB4k4JhzwfW6FpgXuLenvvRogyZARPCLM-zT0uE2xmw3ZVBnxW0ljn0RNW0HWDRylbXEPnfbRbDVzHla--YbZKMZRAKumRKdw0OlbvHj_gxoeyvAit1buYduWRsf1aQkuzXfsUxGbskFd4JacrPDtKvxgEP68t3Cw5WYA",
        "13007", "Test", new Date()));
    }   
}
